export * from './auth/auth.model';
export * from './barber/barber.model';
export * from './cep/cep.model';
export * from './file/file.model';
export * from './generic';
export * from './notify/notify.model';
export * from './service/service.model';
export * from './user/user.model';
export * from './worker/worker.model';
